name: aoc21
synopsis: Aoc
description: Please see the README at <https://github.com/Stoeffel/aoc21/tree/trunk/#readme>.
author: stoeffel
version: 0.0.0.1
maintainer: schtoeffel@gmail.com
copyright: stoeffel
github: stoeffel/aoc21
license-file: LICENSE
category: Web
extra-source-files:
  - README.md
  - LICENSE
executables:
  aoc:
    dependencies:
      - psqueues >= 0.2.7.2 && < 0.3
      - mtl
      - hashable
      - async >= 2.2.2 && < 2.3
      - ansi-terminal
      - attoparsec >= 0.13.2 && < 0.14
      - base >= 4.12.0.0 && < 4.16
      - binary >= 0.8.8.0 && < 0.8.9
      - bytestring >= 0.10 && < 0.11
      - data-default >= 0.7.1.1 && < 0.8
      - filepath >= 1.4 && < 1.5
      - nri-prelude >= 0.1.0.0 && < 0.7
      - pretty-diff >= 0.4.0.2 && < 0.5
      - pretty-show >= 1.9.5 && < 1.11
      - text >= 1.2.3.1 && < 1.3
      - containers
      - fgl >= 5.7.0.3 && < 5.8
      - logict >= 0.7.1.0 && < 0.8
    main: Main.hs
    source-dirs: 
      - app
      - src
library:
  dependencies:
  - psqueues >= 0.2.7.2 && < 0.3
  - mtl
  - hashable
  - async >= 2.2.2 && < 2.3
  - ansi-terminal
  - attoparsec >= 0.13.2 && < 0.14
  - base >= 4.12.0.0 && < 4.16
  - binary >= 0.8.8.0 && < 0.8.9
  - bytestring >= 0.10 && < 0.11
  - data-default >= 0.7.1.1 && < 0.8
  - filepath >= 1.4 && < 1.5
  - nri-prelude >= 0.1.0.0 && < 0.7
  - pretty-diff >= 0.4.0.2 && < 0.5
  - pretty-show >= 1.9.5 && < 1.11
  - text >= 1.2.3.1 && < 1.3
  - containers
  - fgl >= 5.7.0.3 && < 5.8
  - logict >= 0.7.1.0 && < 0.8
  exposed-modules:
  - Aoc.Day01
  - Aoc.Day02
  - Aoc.Day03
  - Aoc.Day04
  - Aoc.Day05
  - Aoc.Day06
  - Aoc.Day07
  - Aoc.Day08
  - Aoc.Day09
  - Aoc.Day10
  - Aoc.Day11
  - Aoc.Day12
  - Aoc.Day13
  - Aoc.Day14
  - Aoc.Day15
  - Aoc.Day16
  - Aoc.Day17
  - Aoc.Day18
  - Aoc.Day19
  - Aoc.Day20
  - Aoc.Day21
  - Aoc.Day22
  - Aoc.Day23
  - Aoc.Day25
  - Aoc.Grid
  source-dirs: src
tests:
  spec:
    dependencies:
    - psqueues >= 0.2.7.2 && < 0.3
    - mtl
    - hashable
    - containers
    - ansi-terminal
    - fgl >= 5.7.0.3 && < 5.8
    - logict >= 0.7.1.0 && < 0.8
    - aeson >= 1.4.6.0 && < 1.6
    - async >= 2.2.2 && < 2.3
    - attoparsec >= 0.13.2 && < 0.14
    - base >= 4.12.0.0 && < 4.16
    - binary >= 0.8.8.0 && < 0.8.9
    - bytestring >= 0.10 && < 0.11
    - data-default >= 0.7.1.1 && < 0.8
    - directory >= 1.3.6.0 && < 1.4
    - filepath >= 1.4.2.1 && < 1.4.3
    - nri-prelude >= 0.1.0.0 && < 0.7
    - pretty-diff >= 0.4.0.2 && < 0.5
    - pretty-show >= 1.9.5 && < 1.11
    - text >= 1.2.3.1 && < 1.3
    main: Main.hs
    source-dirs:
    - src
    - test
    # We intentionally do not add threaded ghc-options for tests. These would
    # cause tests to run in parallel, which introduces flakiness in this test
    # suite. The suite creates a number of web servers that are supposed to get
    # unique ports, but if we start them in parallel this will not always work.
    ghc-options:
      - -fno-warn-type-defaults
      - -threaded
      - -O2
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
  - ExtendedDefaultRules
  - NumericUnderscores
ghc-options:
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
